name: Sync Gitee Repos To Github

# 设置定时执行和手动触发
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    name: Sync Gitee to GitHub
    runs-on: ubuntu-latest
    steps:

      - name: Sync Gite To Github
        uses: Yikun/hub-mirror-action@v1.1
        with:
          src: gitee/wangmingco
          dst: github/wangmingco
          dst_key: ${{ secrets.DRAGONFLY_SECRET_KEY }}
          dst_token: ${{ secrets.dragonfly_token }}
          static_list: 'dragonfly'
          clone_style: "https"
          debug: true
          account_type: user
          force_update: true
          timeout: 300